title ="FP Dual Panel"
#tutor dashboard
recursosUtiles="Recursos Útiles"
documentacionTitle="Documentación"
tabPreOnboarding="Pre Onboarding"
tabOnboarding="Onboarding"
tabSeguimiento="Seguimiento"
tabCierre="Cierre"
tutorDashboard="Recursos Dashboard"
aprendizDashaboard="Dashboard Aprendiz"
adminRecursosTutorDashboard="Recursos Utiles"
adminTutorDashboard="Dashboard Programa"

#login
username="Email"
password="Contraseña"
forgotPassword="Olvidé mi contraseña"
loginButton="Iniciar Sesión"
logoutButton="Desloguearse"
errorRedirection="Sesion expirada. Redirigiendo a login..."
IncorrectPassword="Email o contraseña incorrectos. Intente nuevamente"
logoutMessage="Deslogueo exitoso"
loginMessage="Sesión iniciada exitosamente"
loginDescription="Por favor, para comenzar inicie sesión"