name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set Google Sheets credentials
      run: echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > credentials.json

